version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app:ro
#    env_file:
#      - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password123
      - DATABASE_NAME=python_api_development_comprehensive
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=7fbfc787b6c63798e4037c207a19a7cb42ba5bee3e986a7f0863485c22bbf4d3aba570c6203c644db11d325ee0413d5892d799d00ce64496cce1fc5e31d0c12f459b04f0054b7eed2610d84c63abee8523ee8189fcbee7f9745ec65d0695fd73694dca1be28fc127a654105347842d7da2342b520c8ebc0c925b41774035bbb2
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db: